document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/base.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/footer.css\'/>");
document.writeln("    <link  href=\'https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\' rel=\'stylesheet\' type=\'text/css\' >");
document.writeln("    <script src=\'https://cdn.bootcss.com/jquery/3.2.1/jquery.js\'></script>");
document.writeln("    <script src=\'https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!--start:尾部开始-->");
document.writeln("<footer>");
document.writeln("    <div class=\'footer-container\'>");
document.writeln("        <div class=\'footer-about\'>");
document.writeln("            <div class=\'footer_ contact\'>");
document.writeln("                <h3>联系我们</h3>");
document.writeln("                <p>联系电话：022-58958811</p>");
document.writeln("                <p>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：m13212212205@163.com</p>");
document.writeln("                <p>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：天津市河东区金地紫云庭13-3-3803</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_ about\'>");
document.writeln("                <h3>关于我们</h3>");
document.writeln("                <p><a href=\'about_us.html\'>公司简介</a></p>");
document.writeln("                <p><a href=\'javascript:void(0)\'>帮助中心</a></p>");
document.writeln("                <p><a href=\'javascript:void(0)\'>加入我们</a></p>");
document.writeln("                <p><a href=\'javascript:void(0)\'>服务咨询</a></p>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_ product\'>");
document.writeln("                <h3>产品与服务</h3>");
document.writeln("                <p>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔商城</a>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔零售</a>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <a href=\'mini_applet.html\'>微信小程序</a>");
document.writeln("                    <a href=\'app.html\'>App大师</a>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔餐饮</a>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔美业</a>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔收银</a>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔批发</a>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <a href=\'javascript:void(0)\'>赤兔医药</a>");
document.writeln("                    <a href=\'javascript:void(0)\'>全员开店</a>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_\'>");
document.writeln("                <h3>微信公众平台</h3>");
document.writeln("                <p class='qr-code'></p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");
document.writeln("</body>");
document.writeln("</html>");