document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/header.css\'/>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!--strat: 导航条部分-->");

document.writeln("<nav class=\'navbar navbar-default navbar-fixed-top\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\'>");
document.writeln("                <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'#\'>");
document.writeln("                <img src=\'images/ct_logo.png\' alt=\'\'>");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <!-- Collect the nav links, forms, and other content for toggling -->");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li><a href=\'index.html\'>首页</a></li>");
document.writeln("                <li><a href=\'ct_product.html\'>产品介绍</a></li>");
document.writeln("                <li><a href=\'mini_applet.html\'>微信小程序</a></li>");
document.writeln("                <li><a href=\'website.html\'>网站建设</a></li>");
document.writeln("                <li><a href=\'social_ad.html\'>微信社交广告</a></li>");
document.writeln("                <li><a href=\'app.html\'>APP开发</a></li>");
document.writeln("                <li><a href=\'about_us.html\'>关于我们</a></li>");
document.writeln("            </ul>");
document.writeln("        </div><!-- /.navbar-collapse -->");
document.writeln("    </div><!-- /.container-fluid -->");
document.writeln("</nav>");
document.writeln("</body>");
document.writeln("</html");