document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link  href=\'https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\' rel=\'stylesheet\' type=\'text/css\' >");
document.writeln("    <link rel=\'stylesheet\' href=\'css/base.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/header.css\'/>");
document.writeln("    <script src=\'https://cdn.bootcss.com/jquery/3.2.1/jquery.js\'></script>");
document.writeln("    <script src=\'https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!--strat: 导航条部分-->");
document.writeln("<div class=\'navbar navbar-default navbar-fixed-top\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#ct-navbar-collapse-1\'>");
document.writeln("                <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'#\'>");
document.writeln("                <img src=\'images/ct_logo.png\' alt=\'Brand\'/>");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("        <div class=\'navbar-collapse collapse ct-nav\' id=\'#ct-navbar-collapse-1\' style=\'float: right\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li><a href=\'index.html\'>首页</a></li>");
document.writeln("                <li id=\'mini_applet\'>");
document.writeln("                    <a href=\'ct_product.html\' target=\'_blank\'>产品介绍</a>");
document.writeln("                </li>");
document.writeln("                <li id=\'spaces-dropdown\'>");
document.writeln("                    <a href=\'mini_applet.html\'>微信小程序</a>");
document.writeln("                </li>");
document.writeln("                <li id=\'solution-dropdown\'>");
document.writeln("                    <a href=\'website.html\' target='_blank'>网站建设</a>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'javascript:void(0)\'>微信社交广告</a></li>");
document.writeln("                <li><a href=\'app.html\'>APP开发</a></li>");
document.writeln("                <li><a href=\'javascript:void(0)\'>关于我们</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html");